/* 
* = player
w = wxits
# = corners
# = walls
0 = start
1 = end
d = decorations
r = stones
w = eau
s = sable

p = pirahna
m = méduse
k = kalamars
c = crabes

h = hearth
j = ham
v = palmes

$ = courone
£ = trident
& = perle

ù = boss
*/


export let maps = {
  0: { // Etage 0
    0: [ // Random 0
      'sssssssssssssssssssssssssssssssssssssssss',
      'sssssssssssssssssssssssssssssssssssssssss',
      'sssssssssssssssssssssssssssssssssssssssss',
      'ssssssssssssssssssss*ssssssssssssssssssss',
      'sssssssssssssssssssssssssssssssssssssssss',
      'sssssssssssssssssssssssssssssssssssssssss',
      'sssssssssssssssssssssssssssssssssssssssss',
      'sssssssssssssssssssssssssssssssssssssssss',
      'sssssssssssssssssssssssssssssssssssssssss',
      'sssssssssssssssssssssssssssssssssssssssss',
      'swswsssssssswwswwswsswswswswssssswswsssss',
      'swwwwsswsswswwswwwwsswwwwwswsswswswssswss',
      'wwwwwswwwwwswwswwwwwwwwwwwwwssswwwwwwwsws',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww'
    ]
  },
  1: { //crabe
    0: [
      "   ###########################   ",
      "  # * d #     d #    d  #d  d #  ",
      " #     d#  d    #  d    #  d& d# ",
      "# d     e    c  e       #d      #",
      "# c     e   d   e       # d   d #",
      "#   @   e       e  d    #       #",      
      "# d     #    d  #     r # c d c #",
      "#     d # d     #  c    #       #",
      "###eee#############eee#####eee###",
      "#       #   d   #       #       #",
      "#   d   # d     #   r c #  d  c #",
      "#      d#  c    e       e c   d #",
      "#d      #       e d     e  d    #",
      "#       #   d   e  d    e   c   #",
      "#    d  # d     #c      # d     #",
      "#       #       #    d  #     d #",
      "###eee#############eee###########",
      "#       #     d #       # rd   r#",
      "#    d  # d     #  d c  #       #",
      "# d c   #   d   e    d  e    r  #",
      "#       #       ec      e   r   #",
      "#    d  #   d   e     d e       #",
      "#     d #       #  c    #   c  r#",
      "#       #     d #  d    # r     #",
      "###eee#####eee#############eee###",
      "#     d #       # d     #     r #",
      "#d      # d    d#    d  #r  c   #",
      "#  c    e   c   #       e   d   #",
      "#   d   e     d # d     e  c    #",
      "#       e       #       e    c  #",
      " #d  c  #  d    #    d  # d     #",
      "  #     #      d#       #     d #",
      "   #################1#######   # ",
      "                   ###      ##   ",
    ],
    1:[
      "   ###########################   ",
      "  #     #    d  #   *  d#     #  ",
      " #    d #  d  d # d     #  d   # ",
      "#       e   c   e       e     d #",
      "# d  d  e d     e       e  d    #",
      "# c     e     d e  m d  e       #",
      "#     d # c d   # d     #  d d  #",
      "# d     #    d  #       #d      #",
      "###eee#############eee###########",
      "#     d #    d  #     d #  d    #",
      "#d      # d     # d     #       #",
      "#   d   e    d  e   c   #d  d   #",
      "#       e  d    e       #     d #",
      "# d     e       e    d  # d     #",
      "#   c   #  d    #  c    #      d#",
      "#    d  #     d # d  d  # d     #",
      "###########eee###################",
      "#    d  #     d #  d    #  d    #",
      "#  d    # c     #     d #   d d #",
      "#       e   d   #  c    e       #",
      "#d   d  e     d #       e  d   1#",
      "#  d    e       # d   c e       #",
      "#       # d  c  #    d  #    d  #",
      "#     d #       #       #       #",
      "###########eee#####eee###########",
      "#  d d  #    d  #     d #    d  #",
      "# d&    #   c   # d    d# d     #",
      "#  d  d e d     e   c   e    d  #",
      "#d      e     d e       e       #",
      "#    d  e   d   e    d  e  d    #",
      " #      #  c    #  d    #     d# ",
      "  #d    #d    d #      d#     #  ",
      "   ###########################   ",
    ],
  },
  2: { //pirahna
    0:[
      "   ###########################   ",
      "  #     #    pd #   *   #     #  ",
      " #d  d  # d     # d  @  #      # ",
      "# @     #   d   e    d  e  d    #",
      "#  d    #       e       e       #",
      "#d      #       e  @    e    d  #",
      "#       #  d    #    d  #       #",
      "#     d #       # d     # d     #",
      "###eee#############eee###########",
      "#     d #       #     d #     d #",
      "# d     # d     #d      #  d    #",
      "#       e       e       e   p   #",
      "#    d  e       e  d    e       #",
      "#       e    d  e       e    d  #",
      "# d     #       # d     #dp     #",
      "#   d   #  d    #     d #     d #",
      "###################eee#####eee###",
      "#       #   d   #      d#     d #",
      "#  p    #       #       # d     #",
      "#     d e    d  # d     e    p  #",
      "# d p   e       #       e     d #",
      "#       e       #    d  e       #",
      "#       #  d    #d      #  d    #",
      "#   d   #       #       #      d#",
      "###eee#####eee#####eee###########",
      "#    d  #     d #     d #   d   #",
      "#d      # d     # d  d  #d     @#",
      "#       #   p   e       e       #",
      "#  d    # d     e   d   e       #",
      "#     d #       e   p   e   d p #",
      "#1      #   d   #  d    #      # ",
      " ##     #       #       # d   #  ",
      "   ###########################   ",
    ],/*
    1:[
      "   #################0#########   ",
      "  #     #       #   *   #     #  ",
      " #      #       #       #      # ",
      "#       #       e       e       #",
      "#       #       e       e       #",
      "#       #       e       e       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "###################eee###########",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#################################",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#################################",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      " #      #       #       #      # ",
      "  #     #       #       #     #  ",
      "   ###########################   ",
    ],*/
  },
  3: { //pieuvres       (treasure)
    0:[
      "   ###########################   ",
      "  #     #     d #     d #     #  ",
      " #    d # d  p  #  d    # d   *# ",
      "#   d   e       e       e    d  #",
      "#       e   d   e       e   d   #",
      "# d   @ e       e   d   ed     d#",
      "# d     #d      #       #  d    #",
      "#   d   #  p   d#d    d #       #",
      "###eee#############eee#####eee###",
      "#      d#    d  #      d#     d #",
      "#    d  #  d    #  d    #  d    #",
      "# d   p e     d e       #       #",
      "#       e   d   e  p d  #   @ d #",
      "#  p d  e       ed      # d     #",
      "#     d # d    d#     d #   d   #",
      "#d      #       #p    @ #     d #",
      "###eee#####eee#####eee#####eee###",
      "#      d#     d #       #    d  #",
      "#d      #    d  #d   d  # d     #",
      "#    @ k # d     #   d   #    d  #",
      "# d     #    p  #       #   p   #",
      "#   d   #  d    #  d    #    d  #",
      "#   $   #     d #     d #       #",
      "#    d  #       # d     #d      #",
      "###########eee#####eee#####eee###",
      "#     d #      d#       # d   d #",
      "#  d    #   d   #  d  d #       #",
      "#     d e d     #       e  d    #",
      "#   d   e      d#   p   e     d #",
      "#d      e  d    # d   d e d     #",
      " #1     #       #   d   #    @ # ",
      "  #d @ d#  d  d #       #     #  ",
      "   ###########################   ",
    ],/*
    1:[
      "   #################0#########   ",
      "  #     #       #   *   #     #  ",
      " #      #       #       #      # ",
      "#       #       e       e       #",
      "#       #       e       e       #",
      "#       #       e       e       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "###################eee###########",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#################################",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#################################",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      " #      #       #       #      # ",
      "  #     #       #       #     #  ",
      "   ###########################   ",
    ],*/
  },
  4: { //méduses        (treasure)
    0:[
      "   ###########################   ",
      "  #    d# d  d  #   *   #     #  ",
      " #d  d  #   @   #    d  #d d   # ",
      "#       #  d    e d     e      d#",
      "#   d d # m   d e   @  de    d  #",
      "#d      #       e       e   d   #",
      "#   d   #  d  d #     d #     @ #",
      "#       #       #  d    # d     #",
      "###eee#############eee#####eee###",
      "#       #    d  #d   d  #d     d#",
      "# d  @  # d     # @     #  m    #",
      "#       #    d  e  d    e   d   #",
      "#1      #  d    e     d e     d #",
      "#     d #d    d e    m  e d     #",
      "#  d    # £d    #d      #     @ #",
      "#       #     d #       # d     #",
      "###eee#############eee#####eee###",
      "#     d # d     #d     d#     d #",
      "#m      #    d@ #       #dd     #",
      "#    d  e   d   #    d  #      d#",
      "#d      e    d  #   m   #       #",
      "#   d   e m     #  d    #  d   m#",
      "#   @ d #  d    #d      #       #",
      "#d      #    d  #    d m# d  d  #",
      "###########eee#####eee#####eee###",
      "#       #    d  # d     #d  d   #",
      "#       # d     #  @  d #      d#",
      "#       #   d   ed      e   d   #",
      "#       #    m  e   d   e    m  #",
      "#       # d   d e    d  e d   d #",
      " #      #d      #  d   @#      # ",
      "  #     #    d  # d     #  d  #  ",
      "   ###########################   ",
    ],/*
    1:[
      "   #################0#########   ",
      "  #     #       #   *   #     #  ",
      " #      #       #       #      # ",
      "#       #       e       e       #",
      "#       #       e       e       #",
      "#       #       e       e       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "###################eee###########",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#################################",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#################################",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      "#       #       #       #       #",
      " #      #       #       #      # ",
      "  #     #       #       #     #  ",
      "   ###########################   ",
    ],*/
  },
  5 :{ //boss
    0:[
      "      ##      ",
      "    ##  ##    ",
      "   #d  d  #   ",
      "  #        #  ",
      "  #  d   d #  ",
      " #     ù    # ",
      " # d    d   # ",
      "  #        #  ",
      "  #d ####  #  ",
      "   #  * d #   ",
      "    ##  ##    ",
      "      ##      ",
    ],
  }
}
 

